# Generated by Django 4.2.7 on 2025-08-20 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_delivered_at_chatmessage_read_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='delivered_at',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='read_at',
        ),
    ]
